### ISSUE TITLE
Maybe refactor scope filter into web component?

### ISSUE THREAD

**Issue by tunglinn** [ParkingReformNetwork/reform-map#227]
Part of #186 
Do this before adding new filters

**Comment by Eric-Arellano** [comment]
Turns out Handlebars and Parcel is pretty unmaintained, and the other templates like Pug didn't seem super compelling. 

Instead, I'm thinking a better solution is to use the standardized Web Components. Lit makes this pretty easy: https://lit.dev/docs/v3/getting-started/. But before committing to this, I think we should figure out https://github.com/ParkingReformNetwork/reform-map/issues/228. I'm curious if it will result in us wanting/needing to switch to an already existing library, which would make a web component less necessary.

**Comment by Eric-Arellano** [comment]
Not necessary. See https://github.com/ParkingReformNetwork/reform-map/pull/256.
