### ISSUE TITLE
Add better UX for filter

### ISSUE THREAD

**Issue by tunglinn** [ParkingReformNetwork/reform-map#228]
Part of #186 

We want to mimic the user interface in Shiny. Clicking on a selected item will deselect it, while keeping everything else selected.

Idea: change every normal "click" into a ctrl/cmd + "click"

**Comment by Eric-Arellano** [comment]
> Idea: change every normal "click" into a ctrl/cmd + "click"

I recommend seeing how others have tried solving the problem. With web dev, it's important to follow the best practices because it helps with accessibility, security, and performance.It's not enough for something to work on your local machine because the web is so diverse, like mobile and screen readers.

**Comment by tunglinn** [comment]
Taking inspiration from this: https://codepen.io/gmkhussain/pen/ozwwPw
