### ISSUE TITLE
Triage some cities not rendering when filter set because they don't have values

### ISSUE THREAD

**Issue by Eric-Arellano** [ParkingReformNetwork/reform-map#260]
Follow up on https://github.com/ParkingReformNetwork/reform-map/pull/256 

From a DM with Tung:

> some cities have no value for scope or implementation stage

**Comment by tunglinn** [comment]
List of cities that are missing some values or have values that we don't check for:
- Woodburn, IN (Land Uses: Other, Medical)
- Cohasset, MN (Land Uses: Industrial)
- Ketchum, ID (Land Uses: Low Density (SF) Residential, Commercial)
- ...
(37 in total)

The following are white markers, which are almost impossible to find on the map (due to missing scope value)
- Lower Macungie Township, PA (missing all)
- Long Beach, CA (missing Scope of Reform)
